# Generated by Django 4.0.4 on 2022-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0010_donation_is_taken_alter_donation_address_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='address_1',
            field=models.CharField(max_length=128, verbose_name=('address',)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='address_2',
            field=models.CharField(blank=True, max_length=128, verbose_name=('address cd',)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_taken',
            field=models.CharField(default='Oczekuje na odbiór', max_length=32),
        ),
    ]
